CXXFLAGS=-std=c++17 -O2 -Wformat -Wformat-security -Wignored-qualifiers -Winit-self -Wswitch-default -Wfloat-equal -Wshadow -Wpointer-arith -Wtype-limits -Wempty-body -Wlogical-op -Wmissing-field-initializers -Wnon-virtual-dtor -Wstrict-null-sentinel -Wold-style-cast -Woverloaded-virtual -Wsign-promo -Weffc++ -Wctor-dtor-privacy -Werror -pthread

all : part1
.PHONY: all test clean

test : part1
	./part1

clean :
	rm -rf part1
